Inputs:
    - jetImage
    
Labels:
    - j_g
    - j_q
    - j_w
    - j_z
    - j_t
    
KerasModel: three_layer_modelBEN
KerasModelRetrain: three_layer_model_constraintBEN
KerasLoss: categorical_crossentropy
L1Reg: 0.0001
NormalizeInputs: 0
